<?php

namespace Tests;

require __DIR__ . '/boot-test.php';

use PHPUnit\Framework\TestCase;
use Tests\Support\Assertions\Reflection;

abstract class TestBase extends TestCase
{

    use Reflection;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}
